version: '3'

services: ## Define um serviço
  redis_cache:
    image: redis
    command: redis-server --requirepass Redis2022!
    ports:
      - "6379:6379"
    volumes: 
      - cache:/data/redis
    deploy:
      resources:
        limits:
          memory: 2048M
          cpus: '1.5'
        reservations:
          memory: 1024M

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "ourBank2"
    ports:
      - "3306:3306"
    volumes:
      - cache:/data/mysql
    deploy:
      resources:
        limits:
          memory: 2048M
          cpus: '1.5'
        reservations:
          memory: 1024M

volumes:
  cache:
    driver: local
